name: "Feature request"
description: Suggest a new idea for the project
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: What would you like to see?
      description: Describe the feature you want clearly and concisely.
      placeholder: "Ex: It would be helpful if..."
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Why is this needed?
      description: Explain the problem this feature would solve.
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you looked at other options or workarounds?
